# German translations for profitbricks-python-base package
# German messages for profitbricks-python-base.
# Copyright (C) 2013 THE profitbricks-python-base'S COPYRIGHT HOLDER
# This file is distributed under the same license as the profitbricks-python-base package.
# Frank Brehm <frank.brehm@profitbricks.com>, 2013.
#
msgid ""
msgstr ""
"Project-Id-Version: profitbricks-python-base 0.3.11\n"
"Report-Msgid-Bugs-To: frank.brehm@profitbricks.com\n"
"POT-Creation-Date: 2013-01-14 17:31+0100\n"
"PO-Revision-Date: 2013-01-14 17:49+0100\n"
"Last-Translator: Frank Brehm <frank.brehm@profitbricks.com>\n"
"Language-Team: German\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: pb_base/app.py:411
msgid "The application is not complete initialized."
msgstr "Die Anwendung wurde noch nicht vollständig initialisiert."

#: pb_base/app.py:422
#, python-format
msgid "Object '%s' seems not to be completely initialized."
msgstr "Das Objekt '%s' scheint noch nicht vollständig initialisiert worden zu sein."

#: pb_base/app.py:433 pb_base/fork_daemon.py:361
msgid "Ending."
msgstr "Beenden."

#: pb_base/app.py:452
msgid "executing post_run() ..."
msgstr "führe post_run(() aus ..."

#: pb_base/app.py:474
msgid "General options"
msgstr "Allgemeine Optionen"

#: pb_base/app.py:483
msgid "Use colored output for messages."
msgstr "Verwende farbige Ausgabe für Meldungen."

#: pb_base/app.py:489
msgid "Increase the verbosity level"
msgstr "Erhöhen des Ausführlichkeits-Niveaus."

#: pb_base/app.py:495
msgid "Show this help message and exit"
msgstr "Zeigt die Hilfe-Meldung an und beendet sich."

#: pb_base/app.py:501
msgid "Display brief usage message and exit"
msgstr "Stellt eine kurze Meldung zur Verwendung dar und beendet sich."

#: pb_base/app.py:506
#, python-format
msgid "Version of %(prog)s: %s"
msgstr "Programmversion von %%(prog)s: %s"

#: pb_base/app.py:507
msgid "Show program's version number and exit"
msgstr "Stellt die Programmversion dar und beendet sich."

#: pb_base/cfg_app.py:313
msgid ""
"Configuration file to use additional to the standard configuration files."
msgstr ""
"Konfigurationsdatei, die zusätzlich zu den Standard-Konfigurations-Dateien "
"verwendet werden soll"

#: pb_base/cfg_app.py:322
msgid "The encoding character set of the configuration files"
msgstr "Der Encoding-Zeichensatz der Konfigurations-Dateien"

#: pb_base/cfg_app.py:330
msgid ""
"Generates a default configuration, prints it out to STDOUT and exit"
msgstr ""
"Generiert eine Standard-Konfiguration, schreibt diese nach STDOUT "
"und beendet sich."

#: pb_base/cfg_app.py:433
#, python-format
msgid "Read cfg files with character set '%s' ..."
msgstr "Lese Konfigurations-Dateien mit Zeichensatz '%s' ..."

#: pb_base/cfg_app.py:451
msgid "Used config specification:"
msgstr "Verwendete Konfigurations-Beschreibung:"

#: pb_base/cfg_app.py:460
#, python-format
msgid "Reading in configuration file '%s' ..."
msgstr "Lese Konfigurations-Datei '%s' ein ..."

#: pb_base/cfg_app.py:471
msgid "Found configuration:"
msgstr "Gefundene Konfiguration:"

#: pb_base/cfg_app.py:476
msgid "Validation result:"
msgstr "Ergebnis der Validierung:"

#: pb_base/cfg_app.py:480
#, python-format
msgid "Wrong configuration in '%s' found:"
msgstr "Ungültige Konfigurationsanweisung in '%s' gefunden:"

#: pb_base/cfg_app.py:482
msgid "Configuration error"
msgstr "Konfigurationsfehler"

#: pb_base/cfg_app.py:492
msgid "Using merged configuration:"
msgstr "Verwende fusionierte Konfiguration:"

#: pb_base/cfg_app.py:495
msgid "Using configuration:"
msgstr "Verwende Konfiguration:"

#: pb_base/cfg_app.py:515 pb_base/handler/df.py:453 pb_base/handler/fuser.py:188
msgid "Undefined error"
msgstr "Undefinierter Fehler"

#: pb_base/cfg_app.py:537
#, python-format
msgid "In section %(section)s key '%(key)s': %(value)s"
msgstr "In Abschnitt %(section)s Schlüssel '%(key)s': %(value)s"

#: pb_base/daemon.py:172
#, python-format
msgid "Invalid facility name '%s' given."
msgstr "Ungültiger Facility-Name '%s' angegeben."

#: pb_base/daemon.py:408
#, python-format
msgid "The syslog facility to use when logging as a daemon (default: %s)."
msgstr ""
"Die zu verwendende Syslog-Facility, wenn die Anwendung als Daemon laufen "
"soll (Default: %s)."

#: pb_base/daemon.py:418
msgid ""
"Log to console instead to syslog. Don't daemonize the application, "
"running in foreground."
msgstr ""
"Logging zur Konsole anstatt nach Syslog. Die Anwendung soll im Verdergrund"
"anstelle als eines Daemons laufen."

#: pb_base/daemon.py:527
#, python-format
msgid "Got a signal %s."
msgstr "Signal %s empfangen."

#: pb_base/daemon.py:529
#, python-format
msgid "Process with PID %(pid)d got signal %(signal)s."
msgstr "Der Prozess mit der PID %(pid)d hat das Signal %(signal)s empfangen."

#: pb_base/daemon.py:534
msgid "Nothing to do on signal USR1 or USR2."
msgstr "Auf das Signal USR1 oder USR2 brauch ich nichts zu tun."

#: pb_base/daemon.py:542
msgid "Got a signal for forced shutdown."
msgstr "Habe ein Signal zum forcierten Herunterfahren empfangen."

#: pb_base/daemon.py:564
#, python-format
msgid "Exit from %s, so sad ..."
msgstr "Beende %s, schade auch ..."

#: pb_base/daemon.py:581
#, python-format
msgid "Using '%s' as error log file."
msgstr "Verwende '%s' als Fehler-Logdatei."

#: pb_base/daemon.py:584
#, python-format
msgid "Using '%s' as parent directory of error log file."
msgstr "Verwende '%s' als übergeordnetes Verzeichnis der Fehler-Logdatei."

#: pb_base/daemon.py:588
#, python-format
msgid "Log directory '%s' doesn't exists."
msgstr "Das Log-Verzeichnis '%s' existiert nicht."

#: pb_base/daemon.py:592
#, python-format
msgid "Log directory '%s' exists, but is not a directory."
msgstr "Das Log-Verzeichnis '%s' existiert, ist aber kein Verzeichnis."

#: pb_base/daemon.py:600
#, python-format
msgid "Could not open error logfile: %s"
msgstr "Konnte Fehler-Logdatei nicht öffnen: %s"

#: pb_base/daemon.py:604
#, python-format
msgid "Could not open error logfile %(log)s: %(err)s"
msgstr "Konnte Fehler-Logdatei %(log)s nicht öffnen: %(err)s"

#. do the first fork
#: pb_base/daemon.py:610
msgid "First fork ..."
msgstr "Erster Fork ..."

#: pb_base/daemon.py:617
msgid "Fork #1 failed: "
msgstr "Fork Nr. 1 fehlgeschlagen: "

#. do second fork
#: pb_base/daemon.py:626
msgid "Second fork ..."
msgstr "Zweiter Fork ..."

#: pb_base/daemon.py:633
msgid "Fork #2 failed: "
msgstr "Fork Nr. 2 fehlgeschlagen: "

#: pb_base/daemon.py:636
#, python-format
msgid "%(app)s (v%(ver)s) started as daemon with PID %(pid)d."
msgstr "%(app)s (v%(ver)s) als Daemon mit der PID %(pid)d gestartet."

#. redirect standard file descriptors
#: pb_base/daemon.py:642
msgid "Redirect standard file descriptors ..."
msgstr "Leite Standard-Dateideskriptoren um ..."

#: pb_base/daemon.py:654
msgid "I'm a daemon now - Boooaaaahhh!!!"
msgstr "Ich bin dämonisiert worden, wau - ·▷▶◊◀◁·"

#: pb_base/errors.py:61
#, python-format
msgid "Function %(func)s() has to be overridden in class '%(cls)s'."
msgstr "Die Funktion %(func)s() muss in der Klasse '%(cls)s' überschrieben werden."

#: pb_base/errors.py:92
#, python-format
msgid " (timeout after %0.1f secs)"
msgstr " (Timeout nach %0.1f Sekunden)"

#: pb_base/errors.py:118
msgid "Timeout error on reading"
msgstr "Timeout beim Lesen"

#: pb_base/errors.py:139
msgid "Timeout error on writing"
msgstr "Timeout beim Schreiben"

#: pb_base/fork_daemon.py:254
#, python-format
msgid "Wrong value for max_children %(val)d, must be between 1 and %(max)d."
msgstr ""
"Ungültiger Wert für max_children %(val)d, er muss zwischen 1 und %(max)d liegen."

#: pb_base/fork_daemon.py:275
#, python-format
msgid "Wrong value for timeout_collect_children %d, must be greater than zero."
msgstr ""
"Ungültiger Wert für timeout_collect_children %d, er muss größer als Null sein."

#: pb_base/fork_daemon.py:354
msgid "Cleaning up ..."
msgstr "Räume auf ..."

#: pb_base/fork_daemon.py:364
#, python-format
msgid "Daemon (v%s) ended."
msgstr "Daemon-Prozess (v%s) beendet."

#: pb_base/fork_daemon.py:391
msgid "Collecting all child processes ..."
msgstr "Sammle alle Kind-Prozesse zusammen ..."

#: pb_base/fork_daemon.py:394
msgid "Collecting finished child processes ..."
msgstr "Sammle alle beendeten Kind-Prozesse zusammen ..."

#: pb_base/fork_daemon.py:398
msgid "No active children found."
msgstr "Keine aktiven Kind-Prozesse gefunden."

#: pb_base/fork_daemon.py:430
#, python-format
msgid "Sending signal %d to all child processes."
msgstr "Sende Signal %d an alle Kind-Prozesse."

#: pb_base/fork_daemon.py:440
#, python-format
msgid ""
"Maximum timeout of %d seconds for waiting on finished child processes reached."
msgstr ""
"Maximalen Timeout von %d Sekunden beim Warten auf beendete Kind-Prozesse erreicht."

#: pb_base/fork_daemon.py:445
#, python-format
msgid "New stage %d in waiting for child processes."
msgstr "Neues Level %d beim Warten auf Kind-Prozesse."

#: pb_base/fork_daemon.py:448
#, python-format
msgid "Waiting for finished children, stage %d."
msgstr "Warte auf beendete Kind-Prozesse, Level %d."

#: pb_base/fork_daemon.py:496
#, python-format
msgid "Removing child %d from active child list ..."
msgstr "Entferne Kind-Prozess %d von der Liste der aktiven Prozesse ..."

#: pb_base/fork_daemon.py:519
msgid "Forking a child process ..."
msgstr "Forke einen Kind-Prozess ..."

#: pb_base/fork_daemon.py:537
#, python-format
msgid "Forked with process ID %d."
msgstr "Mit Prozess-ID %d geforkt."

#: pb_base/fork_daemon.py:544
msgid "And here is the child ..."
msgstr "Und hier ist das Baby ..."

#: pb_base/handler/__init__.py:74
msgid "Unknown OS command."
msgstr "Unbekanntes Betriebssystemkommando."

#: pb_base/handler/__init__.py:81
msgid "Empty command list given."
msgstr "Leere Liste mit Kommandos gegeben."

#: pb_base/handler/__init__.py:95
msgid "Could not found OS command"
msgid_plural "Could not found OS commands"
msgstr[0] "Konnte Betriebssystemkommando nicht finden"
msgstr[1] "Konnte Betriebssystemkommandos nicht finden"

#: pb_base/handler/__init__.py:304
#, python-format
msgid "Searching for command '%s' ..."
msgstr "Suche nach Betriebssystemkommando '%s' ..."

#: pb_base/handler/__init__.py:309
#, python-format
msgid "Command '%s' doesn't exists."
msgstr "Das Betriebssystemkommando '%s' existiert nicht."

#: pb_base/handler/__init__.py:312 pb_base/handler/__init__.py:328
#, python-format
msgid "Command '%s' is not executable."
msgstr "Das Betriebssystemkommando '%s' ist nicht ausführbar."

#: pb_base/handler/__init__.py:333 pb_base/handler/__init__.py:335
#, python-format
msgid "Command '%s' not found."
msgstr "Das Betriebssystemkommando '%s' wurde nicht gefunden."

#: pb_base/handler/__init__.py:417
#, python-format
msgid "Executing %r"
msgstr "Führe %r aus"

#: pb_base/handler/__init__.py:418
msgid "Quiet execution"
msgstr "Stillschweigende Ausführung"

#: pb_base/handler/__init__.py:451 pb_base/handler/__init__.py:472
#, python-format
msgid "Output on %(where)s: %(what)r."
msgstr "Ausgabe an %(where)s: %(what)r."

#: pb_base/handler/__init__.py:477
#, python-format
msgid "Returncode: %s"
msgstr "Rückgabewert %s"

#: pb_base/handler/__init__.py:521 pb_base/handler/__init__.py:591
msgid "File doesn't exists."
msgstr "Die Datei existiert nicht."

#: pb_base/handler/__init__.py:523
msgid "Read permission denied."
msgstr "Lesezugriff verweigert."

#: pb_base/handler/__init__.py:526
#, python-format
msgid "Reading file content of %r ..."
msgstr "Lese Dateiinhalt von %r ..."

#: pb_base/handler/__init__.py:596 pb_base/handler/__init__.py:604
#, python-format
msgid "Write permission to %r denied."
msgstr "Schreibzugriff nach %r verweigert."

#: pb_base/handler/__init__.py:599 pb_base/handler/__init__.py:607
msgid "Write permission denied."
msgstr "Schreibzugriff verweigert."

#: pb_base/handler/__init__.py:611
#, python-format
msgid "Write %(what)r into %(to)r."
msgstr "Schreibe %(what)r nach  %(to)r."

#: pb_base/handler/__init__.py:614
#, python-format
msgid "Writing %r ..."
msgstr "Schreibe %r ..."

#: pb_base/handler/__init__.py:618
#, python-format
msgid "Simulating write into %r."
msgstr "Simuliere Schreiben nach %r."

#: pb_base/handler/__init__.py:626
#, python-format
msgid "Opening '%s' for write unbuffered ..."
msgstr "Öffne '%s' zum ungepufferten Schreiben ..."

#: pb_base/handler/__init__.py:633
#, python-format
msgid "Closing '%s' ..."
msgstr "Schließe '%s' ..."

#: pb_base/handler/df.py:328 pb_base/handler/fuser.py:133
msgid "Initialized."
msgstr "Initialisiert."

#: pb_base/handler/df.py:400
#, python-format
msgid "Checking existence of %r ..."
msgstr "Überprüfe existenz von %r ..."

#: pb_base/handler/df.py:402
#, python-format
msgid "Filesystem object %r doesn't exists."
msgstr "Das Dateisystemobjekt %r existiert nicht."

#: pb_base/handler/df.py:406
#, python-format
msgid "%r is not given as an absolute path."
msgstr "%r wurde nicht mit einer absoluten Pfadangebe übergeben."

#: pb_base/handler/df.py:411
msgid "Calling 'df' for the following objects:"
msgstr "Rufe 'df' für die folgenden Objekte auf:"

#: pb_base/handler/df.py:415
msgid "Calling 'df' for real all filesystems."
msgstr "Rufe 'df' für alle realen Dateisysteme auf."

#: pb_base/handler/df.py:417
msgid "Calling 'df' for local filesystems."
msgstr "Rufe 'df' für alle lokalen Dateisysteme auf."

#: pb_base/handler/df.py:419
msgid "Calling 'df' for all filesystems."
msgstr "Rufe 'df' für alle Dateisysteme auf."

#: pb_base/handler/df.py:458
#, python-format
msgid "Error %(nr)d on getting free space of %(obj)r: %(err)s"
msgstr "Fehler %(nr)d beim Ermitteln des freien Platzes von %(obj)r: %(err)s"

#: pb_base/handler/df.py:464
#, python-format
msgid "Didn't found any usable information in output of %r:"
msgstr "Keine auswertbaren Informationen in der Ausgabe von %r gefunden:"

#: pb_base/handler/df.py:476
#, python-format
msgid "Could not evaluate line %(line)r in output of command %(cmd)r."
msgstr ""
"Konnte Zeile %(line)r in der Ausgabe des Kommandos %(cmd)r nicht auswerten."

#: pb_base/handler/fuser.py:164
#, python-format
msgid ""
"Filesystem object %r doesn't seems to exist. "
"Continue because of the 'force' flag."
msgstr ""
"Das Dateisystemobjekt %r scheint nicht zu existieren. "
"Mache wegen gesetztem 'force'-Flag trotzdem weiter."

#: pb_base/handler/fuser.py:167
#, python-format
msgid "Filesystem object %r doesn't seems to exist."
msgstr "Das Dateisystemobjekt %r scheint nicht zu existieren."

#: pb_base/handler/fuser.py:184
#, python-format
msgid "%r will not be used by some other processes."
msgstr "%r wird nicht von anderen Prozessen verwendet."

#: pb_base/handler/fuser.py:193
#, python-format
msgid "Error %(nr)d on getting fuser information of %(obj)r: %(err)s"
msgstr ""
"Fehler %(nr)d beim Ermitteln der fuser-Informationen von %(obj)r: %(err)s"

#: pb_base/handler/fuser.py:207
#, python-format
msgid "%r is not an integer value usable as PID."
msgstr "%r ist kein Integerwert, der als PID verwendet werden kann."

#: pb_base/pidfile.py:70
#, python-format
msgid "Invalid pidfile '%(pidfile)s' given: %(reason)s"
msgstr "Ungültige PID-Datei %(pidfile)r angegeben: %(reason)s"

#: pb_base/pidfile.py:73
#, python-format
msgid "Invalid pidfile %r given."
msgstr "Ungültige PID-Datei %r angegeben."

#: pb_base/pidfile.py:102
#, python-format
msgid ""
"The pidfile '%(pidfile)s is currently in use by the application "
"with the PID %(pid)d."
msgstr ""
"Die PID-Datei %(pidfile)r ist gegenwärtig durch die Anwendung mit der "
"PID %(pid)d in Verwendung."

#: pb_base/pidfile.py:177
msgid "No filename given on initializing PidFile object."
msgstr "Kein Dateiname bei der Initialisierung des PidFile-Objektes angegeben."

#: pb_base/pidfile.py:271
#, python-format
msgid "Pidfile '%s' doesn't exists, not removing."
msgstr "Die PID-Datei %r existiert nicht und wird deshalb auch nicht gelöscht."

#: pb_base/pidfile.py:277
#, python-format
msgid "Auto removing disabled, don't deleting '%s'."
msgstr ""
"Das automatische Löschen ist deaktiviert, "
"deshalb wird '%s' auch nicht gelöscht."

#: pb_base/pidfile.py:282
#, python-format
msgid "Removing pidfile '%s' ..."
msgstr "Lösche PID-Datei '%s' ..."

#: pb_base/pidfile.py:285 pb_base/pidfile.py:321
msgid "Just kidding .."
msgstr "Ich mach doch nur Spass ..."

#: pb_base/pidfile.py:290
#, python-format
msgid "Could not delete pidfile %(file)r: %(err)s"
msgstr "Konnte PID-Datei %(file)r nicht löschen: %(err)s"

#: pb_base/pidfile.py:310 pb_base/pidfile.py:376
#, python-format
msgid "Invalid PID %(pid)d for creating pidfile %(pidfile)r given."
msgstr "Ungültige PID %(pid)d zum Erstellen der PID-Datei %(pidfile)r übergeben."

#: pb_base/pidfile.py:319
#, python-format
msgid "Deleting pidfile '%s' ..."
msgstr "Lösche PID-Datei '%s' ..."

#: pb_base/pidfile.py:329
#, python-format
msgid "Trying opening '%s' exclusive ..."
msgstr "Versuche, '%s' exklusiv zu öffnen ..."

#: pb_base/pidfile.py:332 pb_base/pidfile.py:387
#, python-format
msgid "Simulation mode - don't real writing in '%s'."
msgstr "Simulationsmodus - kein reales Schreiben nach  '%s'."

#: pb_base/pidfile.py:342
#, python-format
msgid "Error on creating pidfile '%(pidfile)s': %(err)s"
msgstr "Fehler beim Erstellen der PID-Datei '%(pidfile)s': %(err)s"

#: pb_base/pidfile.py:347 pb_base/pidfile.py:400
#, python-format
msgid "Writing %(pid)d into '%(pidfile)s' ..."
msgstr "Schreibe %(pid)d in '%(pidfile)s' hinein ..."

#: pb_base/pidfile.py:370
msgid "Calling recreate() on a not self created pidfile."
msgstr "recreate() für eine nicht selbst erstellte PID-Datei aufgerufen."

#: pb_base/pidfile.py:384
#, python-format
msgid "Trying opening '%s' for recreate ..."
msgstr "Versuche, '%s' zum Recreate zu öffnen ..."

#: pb_base/pidfile.py:395
#, python-format
msgid "Error on recreating pidfile '%(pidfile)s': %(err)s"
msgstr "Fehler beim Wiedererstellen der PID-Datei '%(pidfile)s': %(err)s"

#: pb_base/pidfile.py:431
#, python-format
msgid "Pidfile parent directory '%s' doesn't exists."
msgstr "Verzeichnis '%s' der PID-Datei existiert nicht."

#: pb_base/pidfile.py:435
#, python-format
msgid "Pidfile parent directory '%s' is not a directory."
msgstr "Verzeichnis '%s' der PID-Datei ist kein Verzeichnis."

#: pb_base/pidfile.py:439
#, python-format
msgid "No write access to pidfile parent directory '%s'."
msgstr "Kein Schreibzugriff zum verzeichnis '%s' der PID-Datei."

#: pb_base/pidfile.py:446
msgid "It is not a regular file."
msgstr "Es ist keine reguläre Datei."

#: pb_base/pidfile.py:463
#, python-format
msgid "Reading content of pidfile %r ..."
msgstr "Lese Inhalt der PID-Datei %r ..."

#: pb_base/pidfile.py:481
#, python-format
msgid "No useful information found in pidfile %(file)r: %(line)r"
msgstr "Keine auswertbare Information in PID-Datei %(file)r gefunden: %(line)r"

#: pb_base/pidfile.py:494
#, python-format
msgid "Trying check for process with PID %d ..."
msgstr "Versuche, Prozess mit der PID %d zu überprüfen ..."

#: pb_base/pidfile.py:501
#, python-format
msgid "Process with PID %d anonymous died."
msgstr "Der Prozess mit der PID %d ist anonym gestorben."

#: pb_base/pidfile.py:504
#, python-format
msgid "No permission to signal the process %d ..."
msgstr "Kein Recht, ein Signal zum Prozess mit der PID %d zu senden ..."

#: pb_base/pidfile.py:507
#, python-format
msgid "Unknown error: %r."
msgstr "Unbekannter Fehler: %r."

#: pb_base/pidfile_app.py:195
#, python-format
msgid "Using pidfile: %r."
msgstr "Verwende PID-Datei: %r."

#: pb_base/pidfile_app.py:200
msgid "Initialising PidFile object ..."
msgstr "Initialisiere PidFile-Objekt ..."

#: pb_base/pidfile_app.py:288
#, python-format
msgid "Setting pidfile to %r by configuration."
msgstr "Setze PID-Datei auf Grund der Konfiguration auf %r."

#: pb_base/pidfile_app.py:304
#, python-format
msgid "The name of the pidfile (Default: %s)."
msgstr "Der Name der PID-Datei (Default: %s)."

#: pb_base/pidfile_app.py:319
msgid "Simulation mode, nothing is really done."
msgstr "Simulationsmodus, nichts wird wirklich verändert."

#: pb_base/pidfile_app.py:337
#, python-format
msgid "Setting pidfile to %r by commandline parameter."
msgstr "Setze PID-Datei auf Grund des Kommandozeilenparameters auf %r."

#: pb_base/pidfile_app.py:360
#, python-format
msgid "Creating pidfile %r ..."
msgstr "Erstelle PID-Datei %r ..."

#: pb_base/socket_obj/__init__.py:76
msgid "Timeout error on reading from socket"
msgstr "Timeout beim Lesen vom Sockel"

#: pb_base/socket_obj/__init__.py:95
msgid "Timeout error on writing to socket"
msgstr "Timeout beim Schreiben auf den Sockel"

#: pb_base/socket_obj/__init__.py:164
#, python-format
msgid "Invalid request_queue_size %r, must be between 0 and 5."
msgstr ""
"Ungültiger Wert für request_queue_size %r, er muss zwischen 0 und 5 betragen."

#: pb_base/socket_obj/__init__.py:174
#, python-format
msgid "Invalid buffer size %(bs)r, must be between %(min)d and %(max)d."
msgstr ""
"Ungültige Puffergröße %(bs)r, sie muss zwischen %(min)d und %(max)d betragen."

#: pb_base/socket_obj/__init__.py:333
msgid "Closing socket ..."
msgstr "Schließe Sockel ..."

#: pb_base/socket_obj/__init__.py:343
msgid "Resetting socket connection ..."
msgstr "Setze Sockel-Verbindung zurück ..."

#: pb_base/socket_obj/__init__.py:362
msgid ""
"Cannot send message to the receipient, because the socket connection "
"is interrupted."
msgstr ""
"Kann Nachricht nicht zum Empfänger schicken, da die Sockel-Verbindung"
"unterbrochen wurde."

#: pb_base/socket_obj/__init__.py:373
msgid ""
"Cannot send message to the receipient, because the socket connection "
"is closed."
msgstr ""
"Kann Nachricht nicht zum Empfänger schicken, da die Sockel-Verbindung"
"geschlossen wurde."

#: pb_base/socket_obj/__init__.py:378
#, python-format
msgid "Sending %r to socket."
msgstr "Sende %r zum Sockel."

#: pb_base/socket_obj/__init__.py:393
msgid "Cannot accept connection, socket is not bonded."
msgstr "Kann keine Verbindung akzeptieren, da der Sockel nicht gebunden ist."

#: pb_base/socket_obj/__init__.py:401
#, python-format
msgid "Got a request from '%s'."
msgstr "Anfrage von '%s' erhalten."

#: pb_base/socket_obj/__init__.py:403
msgid "Got a request from somewhere from system."
msgstr "Anfrage von irgendwo aus dem System erhalten."

#: pb_base/socket_obj/__init__.py:424
msgid "Trying to get data ..."
msgstr "Versuche, irgendwie die Daten herauszuziehen ..."

#: pb_base/socket_obj/__init__.py:433
#, python-format
msgid "Got data: %r."
msgstr "Erhaltene Daten: %r"

#: pb_base/socket_obj/__init__.py:438
msgid "Got EOF, counterpart has interrupted ..."
msgstr "EOF erhalten, die gegenseite hat unterbrochen ..."

#: pb_base/socket_obj/__init__.py:489
msgid "Performing input buffer ..."
msgstr "Verarbeite Eingabe-Puffer ..."

#: pb_base/socket_obj/__init__.py:493
#, python-format
msgid "Current input buffer: %r"
msgstr "Aktueller Eingabe-Puffer: %r"

#: pb_base/socket_obj/__init__.py:499
#, python-format
msgid "Got a line: %r"
msgstr "Erhaltene Zeile: %r"

#: pb_base/socket_obj/__init__.py:500
#, python-format
msgid "Current input buffer after read_line(): %r"
msgstr "Aktueller Eingabe-Puffer nach read_line(): %r"

#: pb_base/socket_obj/unix.py:59
#, python-format
msgid "The Unix socket file '%s' was not found."
msgstr ""

#: pb_base/socket_obj/unix.py:70
#, python-format
msgid "Invalid permissions to connect to Unix socket '%s'."
msgstr ""

#: pb_base/socket_obj/unix.py:239
#, python-format
msgid "Removing socket '%s' ..."
msgstr ""

#: pb_base/socket_obj/unix.py:247
#, python-format
msgid "Connecting to Unix Domain Socket '%s' ..."
msgstr ""

#: pb_base/socket_obj/unix.py:251 pb_base/socket_obj/unix.py:282
#, python-format
msgid "The socket is even connected to '%s' ..."
msgstr ""

#: pb_base/socket_obj/unix.py:255 pb_base/socket_obj/unix.py:286
#, python-format
msgid "The application is allready bonded to '%s' ..."
msgstr ""

#: pb_base/socket_obj/unix.py:266
#, python-format
msgid "Error connecting to Unix Socket '%(sock)s': %(err)s"
msgstr ""

#: pb_base/socket_obj/unix.py:278
#, python-format
msgid "Creating and binding to Unix Domain Socket '%s' ..."
msgstr ""

#: pb_base/socket_obj/unix.py:303
#, python-format
msgid "Setting permissions of '%(sock)s' to 0%(perm)o."
msgstr ""

#: pb_base/socket_obj/unix.py:316
#, python-format
msgid "Invalid owner name '%s' for socket creation "
msgstr ""

#: pb_base/socket_obj/unix.py:328
#, python-format
msgid "Invalid group name '%s' for socket creation "
msgstr ""

#: pb_base/socket_obj/unix.py:348
msgid "Only root may change ownership of a socket."
msgstr ""

#: pb_base/socket_obj/unix.py:351
#, python-format
msgid "Setting ownership of '%(sock)s' to "
msgstr ""

#: pb_base/socket_obj/unix.py:357
#, python-format
msgid "Start listening on socket with a queue size of %d."
msgstr ""

#: pb_base/translate.py:40
#, python-format
msgid "Basedir: %r"
msgstr "Basis-Verzeichnis: %r"

#: pb_base/translate.py:41
#, python-format
msgid "Found .mo-file: %r"
msgstr "Gefundene .mo-Datei: %r"

