# German translations for profitbricks-python-base package
# German messages for profitbricks-python-base.
# Copyright (C) 2013 THE profitbricks-python-base'S COPYRIGHT HOLDER
# This file is distributed under the same license as the profitbricks-python-base package.
# Frank Brehm <frank.brehm@profitbricks.com>, 2013.
#
msgid ""
msgstr ""
"Project-Id-Version: profitbricks-python-base 0.5.6\n"
"Report-Msgid-Bugs-To: frank.brehm@profitbricks.com\n"
"POT-Creation-Date: 2014-11-02 09:49+0100\n"
"PO-Revision-Date: 2014-11-02 10:00+0100\n"
"Last-Translator: Frank Brehm <frank.brehm@profitbricks.com>\n"
"Language-Team: German\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: bin/crc64:45
msgid "Crc64-Application object:"
msgstr "Das Crc64-Anwendungsobjekt:"

#: pb_base/app.py:85
#, python-format
msgid "Faked exit to OS. Exit value: %(rv)d, message: %(msg)r"
msgstr ""
"Vorgetäuschter Exit zm Betriebssystem. Exitwert: %(rv)d, Meldung: %(msg)r"

#: pb_base/app.py:309 argparse.py:292
msgid "usage: "
msgstr "Verwendung: "

#: pb_base/app.py:475
msgid "executing pre_run() ..."
msgstr "führe pre_run() aus ..."

#: pb_base/app.py:512 pb_base/app.py:529
msgid "The application is not complete initialized."
msgstr "Die Anwendung wurde noch nicht vollständig initialisiert."

#: pb_base/app.py:422
#, python-format
msgid "Object '%s' seems not to be completely initialized."
msgstr "Das Objekt '%s' scheint noch nicht vollständig initialisiert worden zu sein."

#: pb_base/app.py:433 pb_base/fork_daemon.py:361
msgid "Ending."
msgstr "Beenden."

#: pb_base/app.py:452
msgid "executing post_run() ..."
msgstr "führe post_run() aus ..."

#: pb_base/app.py:474
msgid "General options"
msgstr "Allgemeine Optionen"

#: pb_base/app.py:483
msgid "Use colored output for messages."
msgstr "Verwende farbige Ausgabe für Meldungen."

#: pb_base/app.py:489
msgid "Increase the verbosity level"
msgstr "Erhöhen des Ausführlichkeits-Niveaus."

#: pb_base/app.py:495
msgid "Show this help message and exit"
msgstr "Zeigt die Hilfe-Meldung an und beendet sich."

#: pb_base/app.py:501
msgid "Display brief usage message and exit"
msgstr "Stellt eine kurze Meldung zur Verwendung dar und beendet sich."

#: pb_base/app.py:624
#, python-format
msgid "Version of %%(prog)s: %s"
msgstr "Programmversion von %%(prog)s: %s"

#: pb_base/app.py:507
msgid "Show program's version number and exit"
msgstr "Stellt die Programmversion dar und beendet sich."

#: pb_base/cfg_app.py:313
msgid ""
"Configuration file to use additional to the standard configuration files."
msgstr ""
"Konfigurationsdatei, die zusätzlich zu den Standard-Konfigurations-Dateien "
"verwendet werden soll"

#: pb_base/cfg_app.py:325
msgid "The encoding character set of the configuration files."
msgstr "Der Encoding-Zeichensatz der Konfigurations-Dateien."

#: pb_base/cfg_app.py:332
msgid ""
"Generates a default configuration, prints it out to STDOUT and exit."
msgstr ""
"Generiert eine Standard-Konfiguration, schreibt diese nach STDOUT "
"und beendet sich."

#: pb_base/cfg_app.py:433
#, python-format
msgid "Read cfg files with character set '%s' ..."
msgstr "Lese Konfigurations-Dateien mit Zeichensatz '%s' ..."

#: pb_base/cfg_app.py:451
msgid "Used config specification:"
msgstr "Verwendete Konfigurations-Beschreibung:"

#: pb_base/cfg_app.py:460
#, python-format
msgid "Reading in configuration file '%s' ..."
msgstr "Lese Konfigurations-Datei '%s' ein ..."

#: pb_base/cfg_app.py:471
msgid "Found configuration:"
msgstr "Gefundene Konfiguration:"

#: pb_base/cfg_app.py:476
msgid "Validation result:"
msgstr "Ergebnis der Validierung:"

#: pb_base/cfg_app.py:480
#, python-format
msgid "Wrong configuration in %r found:"
msgstr "Ungültige Konfigurationsanweisung in %r gefunden:"

#: pb_base/cfg_app.py:482
msgid "Configuration error"
msgstr "Konfigurationsfehler"

#: pb_base/cfg_app.py:492
msgid "Using merged configuration:"
msgstr "Verwende fusionierte Konfiguration:"

#: pb_base/cfg_app.py:495
msgid "Using configuration:"
msgstr "Verwende Konfiguration:"

#: pb_base/cfg_app.py:515 pb_base/handler/df.py:453 pb_base/handler/fuser.py:188
msgid "Undefined error"
msgstr "Undefinierter Fehler"

#: pb_base/cfg_app.py:537
#, python-format
msgid "In section %(section)s key '%(key)s': %(value)s"
msgstr "In Abschnitt %(section)s Schlüssel '%(key)s': %(value)s"

#: pb_base/crc64_app.py:77
msgid "Generates a 64 bit checksum for all given positional arguments."
msgstr "Generiert eine 64-Bit Prüfsumme für alle übergebenen Positionsargumente."

#: pb_base/crc64_app.py:111
msgid "The token to generate a CRC64 digest from."
msgstr "Die Zeichenkette, von der das CRC64-Digest generiert werden soll."

#: pb_base/daemon.py:172
#, python-format
msgid "Invalid facility name '%s' given."
msgstr "Ungültiger Facility-Name '%s' angegeben."

#: pb_base/daemon.py:408
#, python-format
msgid "The syslog facility to use when logging as a daemon (default: %s)."
msgstr ""
"Die zu verwendende Syslog-Facility, wenn die Anwendung als Daemon laufen "
"soll (Default: %s)."

#: pb_base/daemon.py:412
msgid "Log to console instead to syslog."
msgstr "Logging zur Konsole anstatt nach Syslog."

#: pb_base/daemon.py:413
msgid "Don't daemonize the application, running in foreground."
msgstr "Die Anwendung soll im Verdergrund anstelle als eines Daemons laufen."

#: pb_base/daemon.py:527
#, python-format
msgid "Got a signal %s."
msgstr "Signal %s empfangen."

#: pb_base/daemon.py:529
#, python-format
msgid "Process with PID %(pid)d got signal %(signal)s."
msgstr "Der Prozess mit der PID %(pid)d hat das Signal %(signal)s empfangen."

#: pb_base/daemon.py:534
msgid "Nothing to do on signal USR1 or USR2."
msgstr "Auf das Signal USR1 oder USR2 brauch ich nichts zu tun."

#: pb_base/daemon.py:542
msgid "Got a signal for forced shutdown."
msgstr "Habe ein Signal zum forcierten Herunterfahren empfangen."

#: pb_base/daemon.py:564
#, python-format
msgid "Exit from %s, so sad ..."
msgstr "Beende %s, schade auch ..."

#: pb_base/daemon.py:581
#, python-format
msgid "Using '%s' as error log file."
msgstr "Verwende '%s' als Fehler-Logdatei."

#: pb_base/daemon.py:584
#, python-format
msgid "Using '%s' as parent directory of error log file."
msgstr "Verwende '%s' als übergeordnetes Verzeichnis der Fehler-Logdatei."

#: pb_base/daemon.py:588
#, python-format
msgid "Log directory '%s' doesn't exists."
msgstr "Das Log-Verzeichnis '%s' existiert nicht."

#: pb_base/daemon.py:592
#, python-format
msgid "Log directory '%s' exists, but is not a directory."
msgstr "Das Log-Verzeichnis '%s' existiert, ist aber kein Verzeichnis."

#: pb_base/daemon.py:600
#, python-format
msgid "Could not open error logfile: %s"
msgstr "Konnte Fehler-Logdatei nicht öffnen: %s"

#: pb_base/daemon.py:604
#, python-format
msgid "Could not open error logfile %(log)s: %(err)s"
msgstr "Konnte Fehler-Logdatei %(log)s nicht öffnen: %(err)s"

#. do the first fork
#: pb_base/daemon.py:610
msgid "First fork ..."
msgstr "Erster Fork ..."

#: pb_base/daemon.py:617
msgid "Fork #1 failed: "
msgstr "Fork Nr. 1 fehlgeschlagen: "

#. do second fork
#: pb_base/daemon.py:626
msgid "Second fork ..."
msgstr "Zweiter Fork ..."

#: pb_base/daemon.py:633
msgid "Fork #2 failed: "
msgstr "Fork Nr. 2 fehlgeschlagen: "

#: pb_base/daemon.py:636
#, python-format
msgid "%(app)s (v%(ver)s) started as daemon with PID %(pid)d."
msgstr "%(app)s (v%(ver)s) als Daemon mit der PID %(pid)d gestartet."

#. redirect standard file descriptors
#: pb_base/daemon.py:642
msgid "Redirect standard file descriptors ..."
msgstr "Leite Standard-Dateideskriptoren um ..."

#: pb_base/daemon.py:654
msgid "I'm a daemon now - Boooaaaahhh!!!"
msgstr "Ich bin dämonisiert worden, wau - ·▷▶◊◀◁·"

#: pb_base/errors.py:65
#, python-format
msgid "Function %(func)s() has to be overridden in class '%(cls)s'."
msgstr "Die Funktion %(func)s() muss in der Klasse '%(cls)s' überschrieben werden."

#: pb_base/errors.py:85
#, python-format
msgid "Invalid call to method %(method)s() in a object of class %(class)r (maybe "
      "not overridden?)."
msgstr "Ungültiger Aufruf der Methode %(method)s() in einem Objekt der Klasse %(class)r "
       "(möglicherweise nicht überschrieben?)."

#: pb_base/errors.py:88
#, python-format
msgid "Given positional arguments: %r."
msgstr "Gegebene Positionsargumente: %r."

#: pb_base/errors.py:89
#, python-format
msgid "Given keyword arguments: %r."
msgstr "Gegebene Schlüsselargumente: %r."

#: pb_base/errors.py:92
#, python-format
msgid " (timeout after %0.1f secs)"
msgstr " (Timeout nach %0.1f Sekunden)"

#: pb_base/errors.py:118
msgid "Timeout error on reading"
msgstr "Timeout beim Lesen"

#: pb_base/errors.py:139
msgid "Timeout error on writing"
msgstr "Timeout beim Schreiben"

#: pb_base/errors.py:172
#, python-format
msgid ""
"Couldn't occupy lockfile %(file)r in %(secs)0.1f seconds with %(tries)d tries."
msgstr ""
"Konnte Lockdatei %(file)r nicht nach %(secs)0.1f Sekunden und %(tries)d "
"Versuchen vereinnahmen."

#: pb_base/fork_daemon.py:254
#, python-format
msgid "Wrong value for max_children %(val)d, must be between 1 and %(max)d."
msgstr ""
"Ungültiger Wert für max_children %(val)d, er muss zwischen 1 und %(max)d liegen."

#: pb_base/fork_daemon.py:275
#, python-format
msgid "Wrong value for timeout_collect_children %d, must be greater than zero."
msgstr ""
"Ungültiger Wert für timeout_collect_children %d, er muss größer als Null sein."

#: pb_base/fork_daemon.py:354
msgid "Cleaning up ..."
msgstr "Räume auf ..."

#: pb_base/fork_daemon.py:364
#, python-format
msgid "Daemon (v%s) ended."
msgstr "Daemon-Prozess (v%s) beendet."

#: pb_base/fork_daemon.py:391
msgid "Collecting all child processes ..."
msgstr "Sammle alle Kind-Prozesse zusammen ..."

#: pb_base/fork_daemon.py:394
msgid "Collecting finished child processes ..."
msgstr "Sammle alle beendeten Kind-Prozesse zusammen ..."

#: pb_base/fork_daemon.py:398
msgid "No active children found."
msgstr "Keine aktiven Kind-Prozesse gefunden."

#: pb_base/fork_daemon.py:430
#, python-format
msgid "Sending signal %d to all child processes."
msgstr "Sende Signal %d an alle Kind-Prozesse."

#: pb_base/fork_daemon.py:440
#, python-format
msgid ""
"Maximum timeout of %d seconds for waiting on finished child processes reached."
msgstr ""
"Maximalen Timeout von %d Sekunden beim Warten auf beendete Kind-Prozesse erreicht."

#: pb_base/fork_daemon.py:445
#, python-format
msgid "New stage %d in waiting for child processes."
msgstr "Neues Level %d beim Warten auf Kind-Prozesse."

#: pb_base/fork_daemon.py:448
#, python-format
msgid "Waiting for finished children, stage %d."
msgstr "Warte auf beendete Kind-Prozesse, Level %d."

#: pb_base/fork_daemon.py:496
#, python-format
msgid "Removing child %d from active child list ..."
msgstr "Entferne Kind-Prozess %d von der Liste der aktiven Prozesse ..."

#: pb_base/fork_daemon.py:519
msgid "Forking a child process ..."
msgstr "Forke einen Kind-Prozess ..."

#: pb_base/fork_daemon.py:537
#, python-format
msgid "Forked with process ID %d."
msgstr "Mit Prozess-ID %d geforkt."

#: pb_base/fork_daemon.py:544
msgid "And here is the child ..."
msgstr "Und hier ist das Baby ..."

#: pb_base/handler/__init__.py:74
msgid "Unknown OS command."
msgstr "Unbekanntes Betriebssystemkommando."

#: pb_base/handler/__init__.py:81
msgid "Empty command list given."
msgstr "Leere Liste mit Kommandos gegeben."

#: pb_base/handler/__init__.py:95
msgid "Could not found OS command"
msgid_plural "Could not found OS commands"
msgstr[0] "Konnte Betriebssystemkommando nicht finden"
msgstr[1] "Konnte Betriebssystemkommandos nicht finden"

#: pb_base/handler/__init__.py:327
#, python-format
msgid "Searching for command '%s' ..."
msgstr "Suche nach Betriebssystemkommando '%s' ..."

#: pb_base/handler/__init__.py:332
#, python-format
msgid "Command '%s' doesn't exists."
msgstr "Das Betriebssystemkommando '%s' existiert nicht."

#: pb_base/handler/__init__.py:335 pb_base/handler/__init__.py:351
#, python-format
msgid "Command '%s' is not executable."
msgstr "Das Betriebssystemkommando '%s' ist nicht ausführbar."

#: pb_base/handler/__init__.py:356 pb_base/handler/__init__.py:358
#, python-format
msgid "Command '%s' not found."
msgstr "Das Betriebssystemkommando '%s' wurde nicht gefunden."

#: pb_base/handler/__init__.py:439
#, python-format
msgid "Executing %r"
msgstr "Führe %r aus"

#: pb_base/handler/__init__.py:442
msgid "Quiet execution"
msgstr "Stillschweigende Ausführung"

#: pb_base/handler/__init__.py:485 pb_base/handler/__init__.py:501
#, python-format
msgid "Decoding %(what)s from %(enc)r."
msgstr "Decodiere %(what)s von Codierung %(enc)r."

#: pb_base/handler/__init__.py:475 pb_base/handler/__init__.py:496
#, python-format
msgid "Output on %(where)s: %(what)r."
msgstr "Ausgabe an %(where)s: %(what)r."

#: pb_base/handler/__init__.py:502
#, python-format
msgid "Returncode: %s"
msgstr "Rückgabewert %s"

#: pb_base/handler/__init__.py:546 pb_base/handler/__init__.py:616
msgid "File doesn't exists."
msgstr "Die Datei existiert nicht."

#: pb_base/handler/__init__.py:548
msgid "Read permission denied."
msgstr "Lesezugriff verweigert."

#: pb_base/handler/__init__.py:551
#, python-format
msgid "Reading file content of %r ..."
msgstr "Lese Dateiinhalt von %r ..."

#: pb_base/handler/__init__.py:621 pb_base/handler/__init__.py:629
#, python-format
msgid "Write permission to %r denied."
msgstr "Schreibzugriff nach %r verweigert."

#: pb_base/handler/__init__.py:524 pb_base/handler/__init__.py:632
msgid "Write permission denied."
msgstr "Schreibzugriff verweigert."

#: pb_base/handler/__init__.py:636
#, python-format
msgid "Write %(what)r into %(to)r."
msgstr "Schreibe %(what)r nach  %(to)r."

#: pb_base/handler/__init__.py:639
#, python-format
msgid "Writing %r ..."
msgstr "Schreibe %r ..."

#: pb_base/handler/__init__.py:643
#, python-format
msgid "Simulating write into %r."
msgstr "Simuliere Schreiben nach %r."

#: pb_base/handler/__init__.py:651
#, python-format
msgid "Opening '%s' for write unbuffered ..."
msgstr "Öffne '%s' zum ungepufferten Schreiben ..."

#: pb_base/handler/__init__.py:658
#, python-format
msgid "Closing '%s' ..."
msgstr "Schließe '%s' ..."

#: pb_base/handler/__init__.py:691
#, python-format
msgid "Dumping data from %(src)r to %(tgt)r ..."
msgstr "Pumpe Daten von %(src)r nach %(tgt)r ..."

#: pb_base/handler/__init__.py:708
#, python-format
msgid "Opening %r for read."
msgstr "Öffne %r zum Lesen"

#: pb_base/handler/__init__.py:712
#, python-format
msgid "Error opening source %(src)r: %(msg)s"
msgstr "Fehler beim Öffnen der Quelle %(src)r: %(msg)s"

#: pb_base/handler/__init__.py:717 pb_base/handler/__init__.py:805
#, python-format
msgid "Opening %r for write"
msgstr "Öffne %r zum Schreiben"

#: pb_base/handler/__init__.py:722
#, python-format
msgid "Error opening target %(tgt)r: %(msg)s"
msgstr "Fehler beim Öffnen des Ziels %(tgt)r: %(msg)s"

#: pb_base/handler/__init__.py:727 pb_base/handler/__init__.py:814
#, python-format
msgid "Copying (buffer size %d Bytes)..."
msgstr "Kopiere (Puffergröße %d Bytes) ..."

#: pb_base/handler/__init__.py:733
#, python-format
msgid "Seeking %(bytes)d Bytes (%(human)s) in input to %(src)r."
msgstr "Springe %(bytes)d Bytes (%(human)s) in Quelle %(src)r."

#: pb_base/handler/__init__.py:738 pb_base/handler/__init__.py:820
#, python-format
msgid "Seeking %(bytes)d Bytes (%(human)s) in output to %(tgt)r."
msgstr "Springe %(bytes)d Bytes (%(human)s) in Ziel %(tgt)r."

#: pb_base/handler/__init__.py:752 pb_base/handler/__init__.py:834
#, python-format
msgid "No space left on output device %r."
msgstr "Kein Platz mehr in Ausgabegerät %r."

#: pb_base/handler/__init__.py:756
#, python-format
msgid "Error copying source %(src)r to target %(tgt)r: %(msg)s"
msgstr "Fehler beim Kopieren der Quelle %(src)r zum Ziel %(tgt)r: %(msg)s"

#: pb_base/handler/__init__.py:764 pb_base/handler/__init__.py:845
#, python-format
msgid "%(bytes)d Bytes (%(human)s) written to output device %(tgt)r."
msgstr "%(bytes)d Bytes (%(human)s) in Ausgabegerät %(tgt)r geschrieben."

#: pb_base/handler/__init__.py:791
#, python-format
msgid "Dumping binary zeroes to %r ..."
msgstr "Pumpe binäre Nullen nach %r ..."

#: pb_base/handler/__init__.py:809
#, python-format
msgid "%(errname)s opening target %(tgt)r: %(msg)s"
msgstr "%(errname)s beim Öffnen des Ziels %(tgt)r aufgetreten: %(msg)s"

#: pb_base/handler/__init__.py:838
#, python-format
msgid "Error dumping binary zeroes to target %(tgt)r: %(msg)s"
msgstr "Fehler beim Pumpen binärer Nullen zum Ziel %(tgt)r: %(msg)s"

#: pb_base/handler/df.py:328 pb_base/handler/fuser.py:133
msgid "Initialized."
msgstr "Initialisiert."

#: pb_base/handler/df.py:400
#, python-format
msgid "Checking existence of %r ..."
msgstr "Überprüfe existenz von %r ..."

#: pb_base/handler/df.py:402
#, python-format
msgid "Filesystem object %r doesn't exists."
msgstr "Das Dateisystemobjekt %r existiert nicht."

#: pb_base/handler/df.py:406
#, python-format
msgid "%r is not given as an absolute path."
msgstr "%r wurde nicht mit einer absoluten Pfadangebe übergeben."

#: pb_base/handler/df.py:411
msgid "Calling 'df' for the following objects:"
msgstr "Rufe 'df' für die folgenden Objekte auf:"

#: pb_base/handler/df.py:415
msgid "Calling 'df' for real all filesystems."
msgstr "Rufe 'df' für alle realen Dateisysteme auf."

#: pb_base/handler/df.py:417
msgid "Calling 'df' for local filesystems."
msgstr "Rufe 'df' für alle lokalen Dateisysteme auf."

#: pb_base/handler/df.py:419
msgid "Calling 'df' for all filesystems."
msgstr "Rufe 'df' für alle Dateisysteme auf."

#: pb_base/handler/df.py:458
#, python-format
msgid "Error %(nr)d on getting free space of %(obj)r: %(err)s"
msgstr "Fehler %(nr)d beim Ermitteln des freien Platzes von %(obj)r: %(err)s"

#: pb_base/handler/df.py:464
#, python-format
msgid "Didn't found any usable information in output of %r:"
msgstr "Keine auswertbaren Informationen in der Ausgabe von %r gefunden:"

#: pb_base/handler/df.py:476
#, python-format
msgid "Could not evaluate line %(line)r in output of command %(cmd)r."
msgstr ""
"Konnte Zeile %(line)r in der Ausgabe des Kommandos %(cmd)r nicht auswerten."

#: pb_base/handler/fuser.py:164
#, python-format
msgid ""
"Filesystem object %r doesn't seems to exist. "
"Continue because of the 'force' flag."
msgstr ""
"Das Dateisystemobjekt %r scheint nicht zu existieren. "
"Mache wegen gesetztem 'force'-Flag trotzdem weiter."

#: pb_base/handler/fuser.py:167
#, python-format
msgid "Filesystem object %r doesn't seems to exist."
msgstr "Das Dateisystemobjekt %r scheint nicht zu existieren."

#: pb_base/handler/fuser.py:184
#, python-format
msgid "%r will not be used by some other processes."
msgstr "%r wird nicht von anderen Prozessen verwendet."

#: pb_base/handler/fuser.py:193
#, python-format
msgid "Error %(nr)d on getting fuser information of %(obj)r: %(err)s"
msgstr ""
"Fehler %(nr)d beim Ermitteln der fuser-Informationen von %(obj)r: %(err)s"

#: pb_base/handler/fuser.py:207
#, python-format
msgid "%r is not an integer value usable as PID."
msgstr "%r ist kein Integerwert, der als PID verwendet werden kann."

#: pb_base/handler/lock.py:93
#, python-format
msgid "Locking directory %r doesn't exists or is not a directory."
msgstr "Das Lockverzeichnis %r existiert nicht oder ist kein Verzeichnis."

#: pb_base/handler/lock.py:119 pb_base/handler/lock.py:751
#, python-format
msgid "Locking directory %r isn't writeable."
msgstr "Das Lockverzeichnis %r ist nicht beschreibbar."

#: pb_base/handler/lock.py:189
msgid "No lockfile given on init of a PbLock object."
msgstr "Keine Lockdatei bei der Initialisierung des PbLock-Objecktes angegeben."

#: pb_base/handler/lock.py:193 pb_base/handler/lock.py:965
#, python-format
msgid "Lockfile %r doesn't exists."
msgstr "Die Lockdatei %r existiert nicht."

#: pb_base/handler/lock.py:198
#, python-format
msgid "Lockfile %r is not a regular file."
msgstr "Die Lockdatei %r ist keine reguläre Datei."

#: pb_base/handler/lock.py:323
#, python-format
msgid "Automatic removing of %r ..."
msgstr "Automatisches Löschen von %r ..."

#: pb_base/handler/lock.py:344
#, python-format
msgid "Refreshing atime and mtime of %r to the current timestamp."
msgstr "Erneuern der atime und der mtime von %r auf den gegenwärtigen Zeitpunkt."

#: pb_base/handler/lock.py:491 pb_base/handler/lock.py:514
#: pb_base/handler/lock.py:537 pb_base/handler/lock.py:561
#: pb_base/handler/lock.py:674 pb_base/handler/lock.py:687
#: pb_base/handler/lock.py:700 pb_base/handler/lock.py:719
#: pb_base/handler/lock.py:952
#, python-format
msgid "Value %(val)r for %(what)s is not a Number."
msgstr "Der Wert %(val)r für %(what)s is keine Zahl."

#: pb_base/handler/lock.py:496 pb_base/handler/lock.py:542
#: pb_base/handler/lock.py:566 pb_base/handler/lock.py:678
#: pb_base/handler/lock.py:704 pb_base/handler/lock.py:723
#: pb_base/handler/lock.py:956
#, python-format
msgid "The value for %(what)s must be greater than zero (is %(val)r)."
msgstr "Der Wert für %(what)s muss größer als Null sein "
"(ist aber %(val)r)."

#: pb_base/handler/lock.py:519 pb_base/handler/lock.py:691
#, python-format
msgid ""
"The value for %(what)s must be greater than or equal to zero "
"(is %(val)r)."
msgstr ""
"Der Wert für %(what)s muss größer oder gleich Null sein "
"(ist aber %(val)r)."

#: pb_base/handler/lock.py:733
#, python-format
msgid "Invalid PID %d given on calling create_lockfile()."
msgstr "Ungültige PID %d beim Aufruf von create_lockfile() angegeben."

#: pb_base/handler/lock.py:743
#, python-format
msgid "Trying to lock lockfile %r ..."
msgstr "Versuche, Lockdatei %r zu locken ..."

#: pb_base/handler/lock.py:745
#, python-format
msgid "Using lock directory %r ..."
msgstr "Verwende Lockverzeichnis %r ..."

#: pb_base/handler/lock.py:774
#, python-format
msgid "Current time difference: %0.3f seconds."
msgstr "Aktuelle Zeitdifferenz: %0.3f Sekunden."

#. Try creating lockfile exclusive
#: pb_base/handler/lock.py:779
#, python-format
msgid "Try %(try_nr)d on creating lockfile %(lfile)r ..."
msgstr "Versuch Nr. %(try_nr)d, Lockdatei %(lfile)r anzulegen ..."

#: pb_base/handler/lock.py:791 pb_base/handler/lock.py:899
#, python-format
msgid "Removing lockfile %r ..."
msgstr "Lösche Lockdatei %r ..."

#: pb_base/handler/lock.py:796 pb_base/handler/lock.py:907
#, python-format
msgid "Error on removing lockfile %(lfile)r: %(err)s"
msgstr "Fehler beim Löschen der Lockdatei %(lfile)r: %(err)s"

#: pb_base/handler/lock.py:809
#, python-format
msgid "Sleeping for %0.1f seconds."
msgstr "Schlafe mal für %0.1f Sekunden."

#. or an int for success
#: pb_base/handler/lock.py:823
#, python-format
msgid "Got a lock for lockfile %r."
msgstr "Habe Lock für Lockdatei %r erhalten."

#: pb_base/handler/lock.py:825
#, python-format
msgid "Write %(what)r in lockfile %(lfile)r ..."
msgstr "Schreibe %(what)r in die Lockdatei %(lfile)r ..."

#: pb_base/handler/lock.py:859
#, python-format
msgid "Trying to open %r exclusive ..."
msgstr "Versuche, %r exklusiv zu öffnen ..."

#: pb_base/handler/lock.py:861
msgid "Simulation mode, no real creation of a lockfile."
msgstr "Simulationsbetrieb, kein reales Schreiben einer Lockdatei."

#: pb_base/handler/lock.py:867
#, python-format
msgid "Error on creating lockfile %(lfile)r: %(err)s"
msgstr "Fehler beim Erstellen der Lockdatei %(lfile)r: %(err)s"

#: pb_base/handler/lock.py:896
#, python-format
msgid "Lockfile %r to remove doesn't exists."
msgstr "Die zu löschende Lockdatei %r existiert nicht."

#: pb_base/handler/lock.py:901
msgid "Simulation mode - lockfile won't removed."
msgstr "Simulationsbetrieb - die Lockdatei wird nicht gelöscht."

#: pb_base/handler/lock.py:911
msgid "Stacktrace"
msgstr "Stacktrace"

#: pb_base/handler/lock.py:961
#, python-format
msgid "Checking lockfile %r ..."
msgstr "Überprüfe Lockdatei %r ..."

#: pb_base/handler/lock.py:969
#, python-format
msgid "No read access for lockfile %r."
msgstr "Kein Lesezugriff auf Lockdatei %r."

#: pb_base/handler/lock.py:973
#, python-format
msgid "No write access for lockfile %r."
msgstr "Kein Schreibzugriff auf Lockdatei %r."

#: pb_base/handler/lock.py:979
#, python-format
msgid "Unusable lockfile %r."
msgstr "Lockdatei %r ist nicht verwendbar."

#: pb_base/handler/lock.py:982
#, python-format
msgid "Process with PID %d is unfortunately dead."
msgstr "Der Prozess mit der PID %d ist unglücklicherweise verschieden."

#: pb_base/handler/lock.py:985
#, python-format
msgid "Process with PID %d is even running."
msgstr "Der Prozess mit der PID %d läuft noch."

#: pb_base/handler/lock.py:990
#, python-format
msgid "Lockfile %(lfile)r is older than %(max)d seconds (%(age)d seconds)."
msgstr ""
"Die Lockdatei %(lfile)r ist älter als %(max)d Sekunden (%(age)d Sekunden)."

#: pb_base/handler/lock.py:993
#, python-format
msgid ""
"Lockfile %(lfile)r is %(age)d seconds old, but not old enough (%(max)d seconds)."
msgstr ""
"Die Lockdatei %(lfile)r ist %(age)d Sekunden alt, aber noch nicht alt genug "
"(%(max)d Sekunden)."

#: pb_base/handler/lock.py:1016
#, python-format
msgid "Trying to open pidfile %r ..."
msgstr "Versuche, PID-Datei %r zu öffnen ..."

#: pb_base/handler/lock.py:1020
#, python-format
msgid "Could not open pidfile %r for reading:"
msgstr "Konnte PID-Datei %r nicht zum Lesen öffnen:"

#: pb_base/handler/lock.py:1033
#, python-format
msgid "First line of pidfile %r was empty."
msgstr "Die erste Zeile der PID-Datei %r war leer."

#: pb_base/handler/lock.py:1044
#, python-format
msgid "Could not interprete %(cont)r as a PID from %(file)r:"
msgstr "Konnte %(cont)r (Inhalt von %(file)r) nicht als PID "
"interpretieren:"

#: pb_base/handler/lock.py:1054
#, python-format
msgid "Invalid PID %(pid)d in %(file)r found."
msgstr "Ungültige PID %(pid)d in %(file)r gefunden."

#: pb_base/pidfile.py:70
#, python-format
msgid "Invalid pidfile '%(pidfile)s' given: %(reason)s"
msgstr "Ungültige PID-Datei %(pidfile)r angegeben: %(reason)s"

#: pb_base/pidfile.py:73
#, python-format
msgid "Invalid pidfile %r given."
msgstr "Ungültige PID-Datei %r angegeben."

#: pb_base/pidfile.py:102
#, python-format
msgid ""
"The pidfile '%(pidfile)s is currently in use by the application "
"with the PID %(pid)d."
msgstr ""
"Die PID-Datei %(pidfile)r ist gegenwärtig durch die Anwendung mit der "
"PID %(pid)d in Verwendung."

#: pb_base/pidfile.py:177
msgid "No filename given on initializing PidFile object."
msgstr "Kein Dateiname bei der Initialisierung des PidFile-Objektes angegeben."

#: pb_base/pidfile.py:271
#, python-format
msgid "Pidfile '%s' doesn't exists, not removing."
msgstr "Die PID-Datei %r existiert nicht und wird deshalb auch nicht gelöscht."

#: pb_base/pidfile.py:277
#, python-format
msgid "Auto removing disabled, don't deleting '%s'."
msgstr ""
"Das automatische Löschen ist deaktiviert, "
"deshalb wird '%s' auch nicht gelöscht."

#: pb_base/pidfile.py:282
#, python-format
msgid "Removing pidfile '%s' ..."
msgstr "Lösche PID-Datei '%s' ..."

#: pb_base/pidfile.py:285 pb_base/pidfile.py:321
msgid "Just kidding .."
msgstr "Ich mach doch nur Spass ..."

#: pb_base/pidfile.py:290
#, python-format
msgid "Could not delete pidfile %(file)r: %(err)s"
msgstr "Konnte PID-Datei %(file)r nicht löschen: %(err)s"

#: pb_base/pidfile.py:310 pb_base/pidfile.py:376
#, python-format
msgid "Invalid PID %(pid)d for creating pidfile %(pidfile)r given."
msgstr "Ungültige PID %(pid)d zum Erstellen der PID-Datei %(pidfile)r übergeben."

#: pb_base/pidfile.py:319
#, python-format
msgid "Deleting pidfile '%s' ..."
msgstr "Lösche PID-Datei '%s' ..."

#: pb_base/pidfile.py:329
#, python-format
msgid "Trying opening '%s' exclusive ..."
msgstr "Versuche, '%s' exklusiv zu öffnen ..."

#: pb_base/pidfile.py:332 pb_base/pidfile.py:387
#, python-format
msgid "Simulation mode - don't real writing in '%s'."
msgstr "Simulationsmodus - kein reales Schreiben nach  '%s'."

#: pb_base/pidfile.py:342
#, python-format
msgid "Error on creating pidfile '%(pidfile)s': %(err)s"
msgstr "Fehler beim Erstellen der PID-Datei '%(pidfile)s': %(err)s"

#: pb_base/pidfile.py:347 pb_base/pidfile.py:400
#, python-format
msgid "Writing %(pid)d into '%(pidfile)s' ..."
msgstr "Schreibe %(pid)d in '%(pidfile)s' hinein ..."

#: pb_base/pidfile.py:370
msgid "Calling recreate() on a not self created pidfile."
msgstr "recreate() für eine nicht selbst erstellte PID-Datei aufgerufen."

#: pb_base/pidfile.py:384
#, python-format
msgid "Trying opening '%s' for recreate ..."
msgstr "Versuche, '%s' zum Recreate zu öffnen ..."

#: pb_base/pidfile.py:395
#, python-format
msgid "Error on recreating pidfile '%(pidfile)s': %(err)s"
msgstr "Fehler beim Wiedererstellen der PID-Datei '%(pidfile)s': %(err)s"

#: pb_base/pidfile.py:431
#, python-format
msgid "Pidfile parent directory '%s' doesn't exists."
msgstr "Verzeichnis '%s' der PID-Datei existiert nicht."

#: pb_base/pidfile.py:435
#, python-format
msgid "Pidfile parent directory '%s' is not a directory."
msgstr "Verzeichnis '%s' der PID-Datei ist kein Verzeichnis."

#: pb_base/pidfile.py:439
#, python-format
msgid "No write access to pidfile parent directory '%s'."
msgstr "Kein Schreibzugriff zum Verzeichnis '%s' der PID-Datei."

#: pb_base/pidfile.py:446
msgid "It is not a regular file."
msgstr "Es ist keine reguläre Datei."

#: pb_base/pidfile.py:463
#, python-format
msgid "Reading content of pidfile %r ..."
msgstr "Lese Inhalt der PID-Datei %r ..."

#: pb_base/pidfile.py:481
#, python-format
msgid "No useful information found in pidfile %(file)r: %(line)r"
msgstr "Keine auswertbare Information in PID-Datei %(file)r gefunden: %(line)r"

#: pb_base/pidfile.py:494
#, python-format
msgid "Trying check for process with PID %d ..."
msgstr "Versuche, Prozess mit der PID %d zu überprüfen ..."

#: pb_base/pidfile.py:501
#, python-format
msgid "Process with PID %d anonymous died."
msgstr "Der Prozess mit der PID %d ist anonym gestorben."

#: pb_base/pidfile.py:504
#, python-format
msgid "No permission to signal the process %d ..."
msgstr "Kein Recht, ein Signal zum Prozess mit der PID %d zu senden ..."

#: pb_base/pidfile.py:507
#, python-format
msgid "Unknown error: %r."
msgstr "Unbekannter Fehler: %r."

#: pb_base/pidfile_app.py:195
#, python-format
msgid "Using pidfile: %r."
msgstr "Verwende PID-Datei: %r."

#: pb_base/pidfile_app.py:200
msgid "Initialising PidFile object ..."
msgstr "Initialisiere PidFile-Objekt ..."

#: pb_base/pidfile_app.py:288
#, python-format
msgid "Setting pidfile to %r by configuration."
msgstr "Setze PID-Datei auf Grund der Konfiguration auf %r."

#: pb_base/pidfile_app.py:304
#, python-format
msgid "The name of the pidfile (Default: %s)."
msgstr "Der Name der PID-Datei (Default: %s)."

#: pb_base/pidfile_app.py:319
msgid "Simulation mode, nothing is really done."
msgstr "Simulationsmodus, nichts wird wirklich verändert."

#: pb_base/pidfile_app.py:337
#, python-format
msgid "Setting pidfile to %r by commandline parameter."
msgstr "Setze PID-Datei auf Grund des Kommandozeilenparameters auf %r."

#: pb_base/pidfile_app.py:360
#, python-format
msgid "Creating pidfile %r ..."
msgstr "Erstelle PID-Datei %r ..."

#: pb_base/socket_obj/__init__.py:76
msgid "Timeout error on reading from socket"
msgstr "Timeout beim Lesen vom Sockel"

#: pb_base/socket_obj/__init__.py:95
msgid "Timeout error on writing to socket"
msgstr "Timeout beim Schreiben auf den Sockel"

#: pb_base/socket_obj/__init__.py:164
#, python-format
msgid "Invalid request_queue_size %r, must be between 0 and 5."
msgstr ""
"Ungültiger Wert für request_queue_size %r, er muss zwischen 0 und 5 betragen."

#: pb_base/socket_obj/__init__.py:174
#, python-format
msgid "Invalid buffer size %(bs)r, must be between %(min)d and %(max)d."
msgstr ""
"Ungültige Puffergröße %(bs)r, sie muss zwischen %(min)d und %(max)d betragen."

#: pb_base/socket_obj/__init__.py:333
msgid "Closing socket ..."
msgstr "Schließe Sockel ..."

#: pb_base/socket_obj/__init__.py:343
msgid "Resetting socket connection ..."
msgstr "Setze Sockel-Verbindung zurück ..."

#: pb_base/socket_obj/__init__.py:362
msgid ""
"Cannot send message to the receipient, because the socket connection "
"is interrupted."
msgstr ""
"Kann Nachricht nicht zum Empfänger schicken, da die Sockel-Verbindung"
"unterbrochen wurde."

#: pb_base/socket_obj/__init__.py:373
msgid ""
"Cannot send message to the receipient, because the socket connection "
"is closed."
msgstr ""
"Kann Nachricht nicht zum Empfänger schicken, da die Sockel-Verbindung"
"geschlossen wurde."

#: pb_base/socket_obj/__init__.py:378
#, python-format
msgid "Sending %r to socket."
msgstr "Sende %r zum Sockel."

#: pb_base/socket_obj/__init__.py:393
msgid "Cannot accept connection, socket is not bonded."
msgstr "Kann keine Verbindung akzeptieren, da der Sockel nicht gebunden ist."

#: pb_base/socket_obj/__init__.py:401
#, python-format
msgid "Got a request from '%s'."
msgstr "Anfrage von '%s' erhalten."

#: pb_base/socket_obj/__init__.py:403
msgid "Got a request from somewhere from system."
msgstr "Anfrage von irgendwo aus dem System erhalten."

#: pb_base/socket_obj/__init__.py:424
msgid "Trying to get data ..."
msgstr "Versuche, irgendwie die Daten herauszuziehen ..."

#: pb_base/socket_obj/__init__.py:433
#, python-format
msgid "Got data: %r."
msgstr "Erhaltene Daten: %r"

#: pb_base/socket_obj/__init__.py:438
msgid "Got EOF, counterpart has interrupted ..."
msgstr "EOF erhalten, die gegenseite hat unterbrochen ..."

#: pb_base/socket_obj/__init__.py:489
msgid "Performing input buffer ..."
msgstr "Verarbeite Eingabe-Puffer ..."

#: pb_base/socket_obj/__init__.py:493
#, python-format
msgid "Current input buffer: %r"
msgstr "Aktueller Eingabe-Puffer: %r"

#: pb_base/socket_obj/__init__.py:499
#, python-format
msgid "Got a line: %r"
msgstr "Erhaltene Zeile: %r"

#: pb_base/socket_obj/__init__.py:500
#, python-format
msgid "Current input buffer after read_line(): %r"
msgstr "Aktueller Eingabe-Puffer nach read_line(): %r"

#: pb_base/socket_obj/tcp.py:50
#, python-format
msgid "The TCP port number must be a positive integer value, not %d."
msgstr "Die TCP Portnummer muss eine positve Integerzahl sein, nicht %d."

#: pb_base/socket_obj/tcp.py:180
#, python-format
msgid "The IP address family must be one of %(a1)r, %(a2)r or %(a3)r."
msgstr "Die TCP-Adressfamile muss eine von %(a1)r, %(a2)r oder %(a3)r sein."

#: pb_base/socket_obj/tcp.py:312
msgid "Cannot connect to an undefined IP address."
msgstr "Kann mich nicht zu einer undefinierten Adresse verbinden."

#: pb_base/socket_obj/tcp.py:316
#, python-format
msgid "Connecting to TCP address %(addr)r, port %(port)d ..."
msgstr "Verbinde zu TCP Adresse %(addr)r, Port %(port)d ..."

#: pb_base/socket_obj/tcp.py:320
#, python-format
msgid "The socket is already connected to %(addr)r, port %(port)d ..."
msgstr "Der Socket ist bereits mit %(addr)r, Port %(port)d verbunden ..."

#: pb_base/socket_obj/tcp.py:325
#, python-format
msgid "The application is allready bonded to %(addr)r, port %(port)d ..."
msgstr "Die nwendung ist bereits auf %(addr)r, Port %(port)d gebunden ..."

#: pb_base/socket_obj/tcp.py:351 pb_base/socket_obj/tcp.py:431
#, python-format
msgid "TCP %s results:"
msgstr "TCP %s Resultate:"

#: pb_base/socket_obj/tcp.py:375
#, python-format
msgid "Could not open socket to %(addr)r, port %(port)d."
msgstr "Konnte keinen Sockel zu %(addr)r, Port %(port)d  öffnen."

#: pb_base/socket_obj/tcp.py:398
#, python-format
msgid "Creating a listening TCP socket on address %(addr)r, port %(port)d ..."
msgstr "Erstelle lauschenden TCP-Sockel auf Adresse %(addr)r, Port %(port)d ..."

#: pb_base/socket_obj/tcp.py:402
#, python-format
msgid "The socket is already connected to address %(addr)r, port %(port)d..."
msgstr "Der Sockel ist bereits mit Adresse %(addr)r, Port %(port)d verbunden ..."

#: pb_base/socket_obj/tcp.py:406
#, python-format
msgid "The application is already bonded to address %(addr)r, port %(port)d..."
msgstr "Die Anwendung ist bereits auf Adresse %(addr)r, Port %(port)d gebunden ..."

#: pb_base/socket_obj/tcp.py:462
#, python-format
msgid "Could not open listening TCP socket on %(addr)r, port %(port)d."
msgstr "Konnte keinen lauschenden TCP-Sockel auf Adresse %(addr)r, Port %(port)d erstellen."

#: pb_base/socket_obj/tcp.py:475
#, python-format
msgid "Binding TCP socket to server address: %s"
msgstr "Binde TCP-Sockel auf Serveradresse: %s"

#: pb_base/socket_obj/unix.py:62
#, python-format
msgid "The Unix socket file %r was not found."
msgstr "Die Unix-Sockeldatei %r wurde nicht gefunden."

#: pb_base/socket_obj/unix.py:73
#, python-format
msgid "Invalid permissions to connect to Unix socket %r."
msgstr "Ungenügend Rechte, um sich mit dem Unix-Sockel %r zu verbinden."

#: pb_base/socket_obj/unix.py:256
#, python-format
msgid "Removing socket file %r ..."
msgstr "Lösche Sockeldatei %r ..."

#: pb_base/socket_obj/unix.py:250
#, python-format
msgid "Connecting to Unix Domain Socket '%s' ..."
msgstr "Verbinde mit Unix-Domain-Sockel '%s' ..."

#: pb_base/socket_obj/unix.py:254 pb_base/socket_obj/unix.py:285
#, python-format
msgid "The socket is already connected to '%s' ..."
msgstr "Der Sockel ist bereits verbunden mit '%s' ..."

#: pb_base/socket_obj/unix.py:258 pb_base/socket_obj/unix.py:289
#, python-format
msgid "The application is already bonded to '%s' ..."
msgstr "Die Anwendung is bereits an '%s' gebunden ..."

#: pb_base/socket_obj/unix.py:269
#, python-format
msgid "Error connecting to Unix Socket '%(sock)s': %(err)s"
msgstr "Fehler beim Verbinden mit dem Unix-Domain-Sockel '%(sock)s': %(err)s"

#: pb_base/socket_obj/unix.py:281
#, python-format
msgid "Creating and binding to Unix Domain Socket '%s' ..."
msgstr "Erstelle und binde an Unix-Domain-Sockel '%s' ..."

#: pb_base/socket_obj/unix.py:306
#, python-format
msgid "Setting permissions of '%(sock)s' to 0%(perm)o."
msgstr "Setze Zugriffrechte von '%(sock)s' auf 0%(perm)o."

#: pb_base/socket_obj/unix.py:319
#, python-format
msgid "Invalid owner name '%s' for socket creation given."
msgstr "Ungültiger Besitzername '%s' zur Erstellung des Sockels angegeben."

#: pb_base/socket_obj/unix.py:331
#, python-format
msgid "Invalid group name '%s' for socket creation given."
msgstr "Ungültigen Gruppennamen '%s' zur Erstellung des Sockels angegeben."

#: pb_base/socket_obj/unix.py:351
msgid "Only root may change ownership of a socket."
msgstr "Nur root darf die Besitzerschaft eines Sockels ändern."

#: pb_base/socket_obj/unix.py:354
#, python-format
msgid "Setting ownership of '%(sock)s' to %(uid)d:%(gid)d ..."
msgstr "Setze die Besitzerschaft von '%(sock)s' auf %(uid)d:%(gid)d ..."

#: pb_base/socket_obj/unix.py:360
#, python-format
msgid "Start listening on socket with a queue size of %d."
msgstr "Beginne am Sockel mit einer Warteschlangengröße von %d zu lauschen."

#: pb_base/translate.py:40
#, python-format
msgid "Basedir: %r"
msgstr "Basis-Verzeichnis: %r"

#: pb_base/translate.py:41
#, python-format
msgid "Found .mo-file: %r"
msgstr "Gefundene .mo-Datei: %r"

#: argparse.py:800
msgid ".__call__() not defined"
msgstr ".__call__() wurde nicht definiert"

#: argparse.py:1084
#, python-format
msgid "unknown parser %r (choices: %s)"
msgstr "Unbekannter Parser %r (Auswahl: %s)"

#: argparse.py:1125
#, python-format
msgid "argument \"-\" with mode %r"
msgstr "Argument »-« mit dem Modus %r"

#: argparse.py:1132
#, python-format
msgid "can't open '%s': %s"
msgstr "Kann '%s' nicht öffnen: %s"

#: argparse.py:1336
#, python-format
msgid "cannot merge actions - two groups are named %r"
msgstr "Kann Aktionen nicht fusionieren - zwei Gruppen wurden %r benannt"

#: argparse.py:1374
msgid "'required' is an invalid argument for positionals"
msgstr "'required' ist ein ungültiges Positionsargument"

#: argparse.py:1395
#, python-format
msgid "invalid option string %r: must start with a character %r"
msgstr "Ungültiger Optionsstring %r: er muss mit dem Zeichen %r beginnen"

#: argparse.py:1415
#, python-format
msgid "dest= is required for options like %r"
msgstr "dest= wird für Optionen wie %r benötigt"

#: argparse.py:1432
#, python-format
msgid "invalid conflict_resolution value: %r"
msgstr "Ungültiger Konfliktlösungswert: %r"

#: argparse.py:1450
#, python-format
msgid "conflicting option string(s): %s"
msgstr "Konkurrierende Optionsstring(s): %s"

#: argparse.py:1514
msgid "mutually exclusive arguments must be optional"
msgstr "Sich gegenseitig ausschließende Argumente müssen optional sein"

#: argparse.py:1584
msgid "positional arguments"
msgstr "Positionsargumente"

#: argparse.py:1585
msgid "optional arguments"
msgstr "Optionale Argumente"

#: argparse.py:1600
msgid "show this help message and exit"
msgstr "Zeigt diesen Hilfebildschirm an und beendet sich"

#: argparse.py:1606
msgid "show program's version number and exit"
msgstr "Zeigt die Versionsnumer des Programms an und beendet sich"

#: argparse.py:1638
msgid "cannot have multiple subparser arguments"
msgstr "Kann nicht mehrere Unterparser-Argumente haben"

#: argparse.py:1690
#, python-format
msgid "unrecognized arguments: %s"
msgstr "Unbekannte Argumente: %s"

#: argparse.py:1787
#, python-format
msgid "not allowed with argument %s"
msgstr "Nicht mit Argument %s erlaubt"

#: argparse.py:1833 argparse.py:1847
#, python-format
msgid "ignored explicit argument %r"
msgstr "Ignoriertes explizites Argument %r"

#: argparse.py:1937
msgid "too few arguments"
msgstr "Zu wenig Argumente"

#: argparse.py:1944
#, python-format
msgid "argument %s is required"
msgstr "Das Argument %s wird benötigt"

#: argparse.py:1958
#, python-format
msgid "one of the arguments %s is required"
msgstr "Eines der Argumente %s wird benötigt"

#: argparse.py:2004
msgid "expected one argument"
msgstr "Es wird genau ein Argument erwartet"

#: argparse.py:2005
msgid "expected at most one argument"
msgstr "Es wird maximal ein Argument erwartet"

#: argparse.py:2006
msgid "expected at least one argument"
msgstr "Es wird wenigstens ein Argument erwartet"

#: argparse.py:2065
#, python-format
msgid "ambiguous option: %s could match %s"
msgstr "Mehrdeutige Option: %s könnte auf %s passen"

#: argparse.py:2127
#, python-format
msgid "unexpected option string: %s"
msgstr "Unerwarteter Optionsstring: %s"

#: argparse.py:2228
#, python-format
msgid "%r is not callable"
msgstr "%r ist nicht aufrufbar"

#: argparse.py:2244
#, python-format
msgid "invalid %s value: %r"
msgstr "Ungültiger %s Wert: %r"

#: argparse.py:2254
#, python-format
msgid "invalid choice: %r (choose from %s)"
msgstr "Ungültige Auswahl: %r (aus %s auswählen)"

#: argparse.py:2347
#, python-format
msgid "%s: error: %s\n"
msgstr "%s: Fehler: %s\n"

